### PR TITLE
Polly text to speech 2

### PR DESCRIPTION
**Pull request by ErasedKyte**
This is my polly feature, that converts text to speech, it basically writes each line as mp3 file, then merges them into one mp3 file as a conversation.

the merged file gets uploaded to an s3 bucket.

### CODE REVIEW

**Comment by Ma-hawaj** [comment]
Try to remove os from the requirements file

**Comment by mzhubail** [comment]
@sahmedkh You can approve this now.

**Comment by mzhubail** [comment]
Few things to note:
- Why do you writes each line as mp3 file, then merge them into one mp3 file as a conversation?  Why not do it all at once?
- In `ApiStack.ts`, don't use endpoint `/` use something more descriptive (e.g. `/conversation-to-audio`, `/transcrive-conversation`).
- Don't use hardcoded values for the conversation, you should take the conversation as input from the request.
- Add a comment for `main` indicating what type of inputs the function expects and what is its output.

@ErasedKyte

**Comment by mzhubail** [comment]
@sahmedkh please share the errors you had here.

**Comment by mzhubail** [comment]
@ErasedKyte when I deploy your code, and try to invoke the api, I get the following error

```
[ERROR] Runtime.UserCodeSyntaxError: Syntax error in module 'Polly': invalid decimal literal (uuid.py, line 138)
Traceback (most recent call last):
  File "/var/task/uuid.py" Line 138
                if not 0 <= time_low < 1<<32L:
```

**Comment by mzhubail** [comment]
@ErasedKyte Why did you add file `Polly.tsx`?  It has errors.

**Review by ThatIsHero — APPROVED** [review]
Works Well

Reviewed by me and @Ma-hawaj

**Pull request merged**
