### PR TITLE
74 writing prompt engineering for grading task 1 questions

### PR DESCRIPTION
**Pull request by mzhubail**

### CODE REVIEW

**Comment by mzhubail** [comment]
Some thing to note
- I've correct the rubric of writing task 1.
- Added a sample task 1.  (More to come, hopefully.)
- I've considered adding a fifth prompt that will summarize all of the feedback.
    The goal with this is (A) to make the feedback more consice and more
    approachable for the student, (B) to give the model a change to correct some
    mistakes it might've made.

    There a couple of problem I'm noticing with this implementation (correct me
    if I'm wrong).  The feedback is not in paragraphs, thus harder to read.  The
    feedback no longer contains examples from the student writing (write 'this'
    instead of 'this').

    You should test this more and see if it's worth it.

**Comment by mzhubail** [comment]
@Ma-hawaj Please mention the work that you told me needs to be done.  This pull request will be merged today _hopefully_.

**Comment by Ma-hawaj** [comment]
We need to extract the grade from bedrock response.
I am thinking of modifying the prompt to use bullet points for the feedback

**Comment by Ma-hawaj** [comment]
Also noticed that the browser request times out after 30s even if the lambda didn't.

**Comment by mzhubail** [comment]
> Also noticed that the browser request times out after 30s even if the lambda didn't.

I didn't find anything in `Amplify` documentation regarding the timeout.  In addition to that, fetch API seems seems to not include timeout for some reason ([see this reddit comment](https://www.reddit.com/r/learnjavascript/comments/mlcnsp/comment/gtkqbnv/).

Good luck!

**Comment by mzhubail** [comment]
> Good for bow but need to look into the timeout issue later.

Maybe create an issue, or add to backlog.

**Comment by mzhubail** [comment]
Note merging this will ruin #80.

**Pull request merged**
