### PR TITLE
79 writing integrating the language tool in both writing tasks grading

### PR DESCRIPTION
**Pull request by Ma-hawaj**

### CODE REVIEW

**Comment by mzhubail** [comment]
@Ma-hawaj how do you run your code? depoly or dev?

When I run it in `dev` the code doesn't work, because the value of `grammerToolDNS` is `'undefined DNS'`.

You should probably handle failure of language tool in a better way.  What I have in mind is to make it optional in response (note the `?`):

```ts
interface Response {
  'Coherence & Cohesion': string;
  'Grammatical Range & Accuracy': string;
  'Lexical Resource': string;
  'Task Responce': string;
  'Grammer Tool Feedback'?: Array<{
    message: string;
    context: { text: string; offset: number; length: number };
  }>;
}
```

And for `runLangTool` give it a return type (current inferred type is `Promise<any>`).  And in writing grading lambda and in interface code, handle the case when the tool fails.

**Comment by Ma-hawaj** [comment]
By default when running dev it doesn't deploy the language tool.
You can go to the api stack and uncomment the commented code to deploy it when running in dev.

**Comment by mzhubail** [comment]
1- Note that I moved `GrammerCheckerTool` into its own stack.

2- Last time I ran your code I'm was faced with this issue:

image

  The simplest way to solve this is by commenting out the service, and hard-coding the tool's url.  But I'm not sure if we should.  @cerashdan @maramesk @Ma-hawaj

**Comment by mzhubail** [comment]
Resolve conflicts and test your code. @Ma-hawaj

**Comment by Ma-hawaj** [comment]
Seems that everything alright but noticed that when the request timeouts it resend it automatically.
I don't know why.

**Comment by mzhubail** [comment]
> Seems that everything alright but noticed that when the request timeouts it resend it automatically. I don't know why.

Where? front-end? lambda?

**Comment by Ma-hawaj** [comment]
Frontend, I think it's something with the browser since I was trying the polly PR and it send the request 3 times if it fails also.

**Review by ErasedKyte — APPROVED** [review]

**Pull request merged**
