### PR TITLE
104 Add Writing Exam Page

### PR DESCRIPTION
**Pull request by mzhubail**

### CODE REVIEW

**Comment by mzhubail** [comment]
@ThatIsHero note in af74924, I have modified the layout of the page.  Take a look at it.

It might be a source of conflicts later.

**Comment by mzhubail** [comment]
@ThatIsHero few things to note:
- My pages currently don't include grading student's answer.
- Will the feedback be displayed in the same page?  If so, how?
- Should I put the feedback in any format for now, so that we have something presentable for the demo?

**Comment by ThatIsHero** [comment]
@mzhubail regarding last notes :

for the feedback I think that it will be better for the design of it to be same as speaking team feedback page as it has from top to bottom:

overall score

score breakdown with a bar that shows the score 


if you click on the section above it will open a tab that have the feedback regarding this specific point

I will share with you the sketch design done by speaking group through Whatsapp

**Comment by ThatIsHero** [comment]
For the pages everything work will 

Designing will be considered later 

but for know at this stage everything is good

Regards

**Comment by xvbilalvx** [comment]
@mzhubail  - Will the feedback be displayed in the same page? If so, how?
im displaying them in the same page, I think we should display them in the same way.

**Comment by mzhubail** [comment]
@ThatIsHero @xvbilalvx for now I've added the feedback in the same page, same as in the dummy page (but with a somewhat better design).

We'll have to revise this later, as with other parts of the design and the codebase.

**Review by ThatIsHero — APPROVED** [review]
Works Well and have been tested

**Pull request merged**
