### PR TITLE
Add authentication

### PR DESCRIPTION
**Pull request by mzhubail**

### CODE REVIEW

**Review by Ma-hawaj — DISMISSED** [review]
Good job for now.
I think the next step is to: 

- Add a custom attribute (institution)
- Add a post sign up lambda that add the student ID to the institution students index and initialize the aggregates for the user in the database

**Comment by mzhubail** [comment]
> Good job for now. I think the next step is to:
> 
>     * Add a custom attribute (institution)
> 
>     * Add a post sign up lambda that add the student ID to the institution students index and initialize the aggregates for the user in the database

[This](https://docs.amplify.aws/javascript/build-a-backend/auth/manage-user-profile/) might be relevant you can add this to the backlog.

**Comment by mzhubail** [comment]
Note that someone has to go through all of the existing API calls and change it to use `Amplify` functions.

**Review by Ma-hawaj — APPROVED** [review]
Good job.

**Comment by mzhubail** [comment]
Done (finally)

Next steps:
- Fix all API calls in front-end
- Add trigger to handle sign-in related tasks (@Ma-hawaj)

**Pull request merged**
