### PR TITLE
77 general collecting question to fill dynamodb in a single script

### PR DESCRIPTION
**Pull request by Ma-hawaj**

### CODE REVIEW

**Comment by Ma-hawaj** [comment]
To use the script just replace the table name and run it.
Be sure to be in the QuestionScript directory when running.

**Comment by mzhubail** [comment]
Quick tip, it would be helpful if you add comments about each variable alongside its declaration (specifically for `TransactItemss` and `indexes`).  Focus on helping the reader understand what each variable will contain.

**Review by mzhubail — APPROVED** [review]
Good job.

Next step is to add writing task 1 questions. remind me.

**Comment by mzhubail** [comment]
Seems good.

If there are any mistakes or stuff that needs to be added, do that later, not in this pull request!

**Review by mzhubail — DISMISSED** [review]

**Review by mzhubail — DISMISSED** [review]

**Review by mzhubail — DISMISSED** [review]
Approve

**Review by mzhubail — DISMISSED** [review]
Approving

**Review by mzhubail — APPROVED** [review]
Approve

**Pull request merged**
