### PR TITLE
Speaking Update Prompt and Handle Scores

### PR DESCRIPTION
**Pull request by mzhubail**
I added @xvbilalvx's changes from #85.  At the time of writing, this branch is up-to-date with `main`.

@sahmedkh there are some issues integrating your changes with his changes.  Please do fix them and make sure everything is working as expected.  You own this PR.

### CODE REVIEW

**Comment by mzhubail** [comment]
@sahmedkh why do you store feedback as a `string` in dynamo?

**Comment by sahmedkh** [comment]
> @sahmedkh why do you store feedback as a `string` in dynamo?

This is how it was done originally, I don't feel like this is the appropriate PR to perform this change. I will add this suggestion to the backlog and work on it later.

**Review by Ma-hawaj — APPROVED** [review]
Good for now.
You may  need to change the approach of extracting the grade since bedrock may write it in other form than 'Score:'.

**Comment by sahmedkh** [comment]
> Good for now. You may need to change the approach of extracting the grade since bedrock may write it in other form than 'Score:'.

Noted. Will add that `mzhubail`'s suggested change

**Pull request merged**
