### PR TITLE
Toast Message and Navigate to Home

### PR DESCRIPTION
**Pull request by DanaK270**
- added "toast" messages to both signin and signup pages

- navigate to home page after successful signin/signup after the toast message is closed

- package was updated to include react-toastify

### CODE REVIEW

**Comment by DanaK270** [comment]
any suggestions are welcome

**Comment by mzhubail** [comment]
@DanaK270 Check my last commit and request an approval from anyone

**Comment by DanaK270** [comment]
👍🏻

**Review by ThatIsHero — APPROVED** [review]
Worked well

**Pull request merged**
