### PR TITLE
Placement Test Modified

### PR DESCRIPTION
**Pull request by ThatIsHero**
Test has been done what it needs:

- Modify the style (will be done in another branch)
- Add more questions 
- Questions need to be moved to the table  (modifying this branch)

still not ready to merge

### CODE REVIEW

**Comment by ThatIsHero** [comment]
I have to go over the design again 
I will do database manage in other branch to make the work cleaner for the revise

**Review by mzhubail — APPROVED** [review]
Works well for now.  UI can use some improvements, but we'll get to that later.

For now I've added a button to toggle dev view.  Check it and merge!

**Comment by ThatIsHero** [comment]
@ErasedKyte

**Review by Ma-hawaj — APPROVED** [review]
Approved by @ThatIsHero @mzhubail

**Pull request merged**
