### PR TITLE
129 speaking   modify speaking front end pages

### PR DESCRIPTION
**Pull request by sahmedkh**

### CODE REVIEW

**Comment by sahmedkh** [comment]
@mzhubail Quite frankly, I'm lost, so if you have any suggestions or comments please do tell me.

**Comment by mzhubail** [comment]
@sahmedkh

I tried running the code of `narrateQuestion` on a test page, and it seems to be working fine in isolation.

### Locating the issue

One thing that comes to mind is that your use of `useEffect` might be causing an issue.  When you the component renders, `useEffect` will run, which contains `set`, which will trigger a render again!

I tried tracking how many times your component renders (see the diff below).  From what I see, when I click on the button the component renders twice, therefore playing audio twice.

```diff
diff --git a/packages/frontend/src/pages/SpeakingConversationPage.tsx b/packages/frontend/src/pages/SpeakingConversationPage.tsx
index b212ac6..2949957 100644
--- a/packages/frontend/src/pages/SpeakingConversationPage.tsx
+++ b/packages/frontend/src/pages/SpeakingConversationPage.tsx
@@ -2,6 +2,8 @@ import { useState, useEffect } from 'react';
 import { getSocketUrl } from '../utilities';
 import useWebSocket from 'react-use-websocket';
 
+let i = 0;
+
 import {
   fetchQuestion,
   narrateQuestion,
@@ -22,6 +24,7 @@ type questionType = {
 // };
 
 export function SpeakingConversationPage() {
+  console.log(i++);
   const [questions, setQuestions] = useState<questionType[]>([]);
   const [currentQuestion, setCurrentQuestion] = useState<questionType>();
   const [recorder, setRecorder] = useState<RecordRTC>();
```

### Moving forward

A couple of things to note.
- You might benefit from moving to something similar to what we're doing.  Take everything you need as a parameter, and make the parent of the component responsible for providing you with what you need.  This can help limit your need for `useEffect` inside your component.
- You might benefit from using this custom hook I found [online](https://stackoverflow.com/questions/47686345/playing-sound-in-react-js) it seems to have a better design.  (Try it and update me on that!)
```ts
import React, { useState, useEffect } from "react";

const useAudio = url => {
  const [audio] = useState(new Audio(url));
  const [playing, setPlaying] = useState(false);

  const toggle = () => setPlaying(!playing);

  useEffect(() => {
      playing ? audio.play() : audio.pause();
    },
    [playing]
  );

  useEffect(() => {
    audio.addEventListener('ended', () => setPlaying(false));
    return () => {
      audio.removeEventListener('ended', () => setPlaying(false));
    };
  }, []);

  return [playing, toggle];
};

const Player = ({ url }) => {
  const [playing, toggle] = useAudio(url);

  return (
    <div>
      <button onClick={toggle}>{playing ? "Pause" : "Play"}</button>
    </div>
  );
};
```
- You might benefit from creating utility components, one for recording and one for playing audio.  The reason I'm suggesting this is so that a change in the state of the recording component will not affect the audio playing component and possibly trigger a re-render.

**Comment by mzhubail** [comment]
@sahmedkh, it seems like the audio wave visualization thing includes the functionality of playing audio. 

@ErasedKyte is doing it in another PR #193.

**Comment by sahmedkh** [comment]
This PR became quite big after rebasing, so it has been moved to PR #218.

**Pull request closed without merging**
