### PR TITLE
Finish Speaking UI

### PR DESCRIPTION
**Pull request by mzhubail**

### CODE REVIEW

**Comment by mzhubail** [comment]
Regarding #262.  It is fixed by 847b680.

- Playing same audio: The cause of this issue is that we run load only
  once, when the component is created.

  This is fixed by moving `load` call to its own `useEffect` with
  `trackIndex` as its dependency so that it will be executed each time
  the `trackIndex` is updated.

- Stop on last audio:  The cause of this issue is that you don't have
  access to the latest `trackIndex`, it is always 0 (the value when we
  run the `useEffect`).

  This is fixed by using a function in `setState`
  (i.e. `setState(prevValue => ...)`).  This gives you access to the
  current value.

**Comment by mzhubail** [comment]
A note e5b6d61.

The button component now supports navigation too.  I propose using this component in our interface for the sake of consistency.

@saraisa12

**Comment by mzhubail** [comment]
@sahmedkh @Ma-hawaj I added a link to a speaking page using the sample full test.  You're welcome.

**Comment by mzhubail** [comment]
Started actually working on speaking :)

**Comment by mzhubail** [comment]
Many major modifications were done

### In `SpeakingQuestionsPage`

I Improved on the structures and variables in the page.  This page now follows the style of the rest of the pages of defining a state and then allow its child to read and modify a part of it (i.e. page contains `response` but the component for part 2 is only allowed to modify `P2` in the state).

It seems to me that this component is feature complete.  Might need some edge roughing, but nothing major.

### In `SpeakingBodyComponent`

Replaced old code for rendering.  The code is now much simpler.

In addition, I added the needed states for allowing a speaking functionality like index and whether to allow student to record or not.  This state is meant to support the correct user flow in the page.  Work is still in progress.

**Comment by mzhubail** [comment]
The general page flow is here.  Next step is to test that it integrates with the full test.

**Comment by mzhubail** [comment]
@xvbilalvx @sahmedkh Confirm on me whether we need either of `SpeakingConversationPage.tsx` `SpeakingExercisesPage.tsx` `SpeakingLongQuestionPage.tsx`.

**Comment by mzhubail** [comment]
Note that I removed the link to page from `/sections`.  This is because I'm using `to` option from #274.

Merge that pull request first!

**Review by Ma-hawaj — APPROVED** [review]

**Pull request merged**
