### PR TITLE
128 speaking   modify speaking back end

### PR DESCRIPTION
**Pull request by sahmedkh**

### CODE REVIEW

**Comment by mzhubail** [comment]
Good work!

**Comment by Ma-hawaj** [comment]
Is the frontend fully functioning in part 1 ?

**Review by Ma-hawaj — APPROVED** [review]
Good for now.
I think you may use another approach for prompting P1 to present it as a conversation.

**Comment by sahmedkh** [comment]
> Good for now. I think you may use another approach for prompting P1 to present it as a conversation.

Yes, I do plan on testing the prompt and adjusting it further.

**Pull request merged**
