### PR TITLE
fixing timeout when exceeding 29s 

### PR DESCRIPTION
**Pull request by Ma-hawaj**

### CODE REVIEW

**Comment by Ma-hawaj** [comment]
Looks like the issue was from the API gateway that limits the request to 29s and seems that it cannot be increased.

**Comment by Ma-hawaj** [comment]
[Tutorial for SST WebSockets](https://sst.dev/examples/how-to-create-a-websocket-api-with-serverless.html)
[To test WebSocket backend](https://piehost.com/websocket-tester)
[React WebSocket documentation](https://www.npmjs.com/package/react-use-websocket)
[Configuring WebSocket routes](https://docs.aws.amazon.com/apigateway/latest/developerguide/websocket-api-develop-routes.html)

**Comment by Ma-hawaj** [comment]
[Good example for authenticating the websocket API](https://github.com/aws-samples/websocket-api-cognito-auth-sample)

**Comment by Ma-hawaj** [comment]
Note that currently the websocket api has no kind of authentication.

**Comment by mzhubail** [comment]
> Note that currently the websocket api has no kind of authentication.

Sure, we may look at it later.  Add it to the backlog.

**Comment by Ma-hawaj** [comment]
> [Good example for authenticating the websocket API](https://github.com/aws-samples/websocket-api-cognito-auth-sample)

This can be used as an example

**Comment by mzhubail** [comment]
@sahmedkh we're finished up fixing this issue for writing.  I think speaking needs the same too.  You can reach out to me after the demo, to work on it together.

**Review by ThatIsHero — APPROVED** [review]
Works well !
Great work guys

**Pull request merged**
